name: Deploy

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      PORT: 3001
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'backend: npm install'
        working-directory: ./backend
        run: npm install
      - name: 'backend: npm run lint'
        working-directory: ./backend
        run: npm run lint
      - name: 'backend: npm test'
        working-directory: ./backend
        run: npm test

      - name: 'frontend: npm install'
        working-directory: ./frontend
        run: npm install
      - name: 'frontend: npm run lint'
        working-directory: ./frontend
        run: npm run lint
      - name: 'frontend: npm test'
        working-directory: ./frontend
        run: npm test -- --watchAll=false
      - name: 'frontend: npm build'
        working-directory: ./frontend
        run: npm build

      - name: deploy
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'fullstackopen-cicd-bloglist'
          heroku_email: 'smulitus@gmail.com'
          remote_branch: master
          healthcheck: 'https://fullstackopen-cicd-bloglist.herokuapp.com/health'
          checkstring: 'ok'

      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch